# Generated by Django 6.0.5 on 2026-05-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='solution_file',
            field=models.FileField(blank=True, null=True, upload_to='task_solutions/'),
        ),
    ]
